name: jojogan_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.12
  - cmake>=3.18
  - pip
  - pip:
      - torch==1.10.0
      - torchvision==0.11.1
      - ninja==1.10.2.3
      - opencv-python==4.5.5.64
      - dlib==19.22.1
      - tqdm==4.62.3
      - gdown==3.6.4
      - scikit-learn==0.22
      - scipy==1.4.1
      - lpips==0.1.4
      - wandb==0.12.9
      - numpy==1.19.5
      - matplotlib==3.2.2
